### ISSUE TITLE
Default community health files

### ISSUE THREAD

**Issue by szepeviktor** [crwlrsoft/graphics#1]
@otsch GitHub now has a feature called _default community health files_.
https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file

Please consider renaming this repo to `.github` and moving images under `images/`.

**Comment by szepeviktor** [comment]
🎉 We already have that! 🥳 

https://github.com/crwlrsoft/.github

Then simply move graphics into that.

**Comment by otsch** [comment]
True, we could move it to the .github repo. But this here has to remain at least for a while, because the logo is already linked in some versions of existing packages.
I just had a look at how laravel is bringing the logo to it's repository readme files, and they're also having a separate art repo: https://github.com/laravel/art 
I guess it won't hurt to have this, so I'll just let it for now.
Maybe I'll take some time to move the `CONTRIBUTING.md` files to the organization's `.github` repo and also move the logo then.

**Comment by szepeviktor** [comment]
> laravel is bringing the logo

For business people more things mean more profit.

For engineers more stuff means more burden.

**Comment by otsch** [comment]
laravel is an open source project and I guess their paid services won't make more money by having an art repository in their organization 😉

At the moment it'd mean more effort for me to move the logo to the other repo, replace the links in all the readme files where it's linked and at some point when all the versions where it was linked are pretty old, just remove this repo.
